/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.edu.ifpr.paranavai.armarios.view;

import br.edu.ifpr.paranavai.armarios.controller.LoginController;
import br.edu.ifpr.paranavai.armarios.view.Bibliotecario;
import java.awt.Button;
import java.awt.Color;
import java.awt.Container;
import java.awt.TextField;
import java.util.Locale;
import javax.swing.JPasswordField;
import javax.swing.JTextField;

/**
 *
 * @author teren
 */
public class Index extends javax.swing.JFrame {

    /**
     * Creates new form AuthEditorUI
     */
    public Index() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        AcessarButton = new javax.swing.JButton();
        passFieldSenha = new javax.swing.JPasswordField();
        DevolverToggleButton = new javax.swing.JToggleButton();
        jLabel1 = new javax.swing.JLabel();
        MostrarSenhaToggleButton = new javax.swing.JToggleButton();
        txtFieldRA = new javax.swing.JTextField();
        lblResposta = new javax.swing.JLabel();
        EmprestarToggleButton = new javax.swing.JToggleButton();
        jLabel2 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Empréstimo e devolução de chaves");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel1MouseClicked(evt);
            }
        });

        AcessarButton.setText("Confirmar");
        AcessarButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AcessarButtonMouseClicked(evt);
            }
        });

        passFieldSenha.setForeground(new java.awt.Color(204, 204, 204));
        passFieldSenha.setText("Digite a senha");
        passFieldSenha.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                passFieldSenhaFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                passFieldSenhaFocusLost(evt);
            }
        });
        passFieldSenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passFieldSenhaActionPerformed(evt);
            }
        });

        DevolverToggleButton.setText("Devolver");
        DevolverToggleButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DevolverToggleButtonMouseClicked(evt);
            }
        });

        jLabel1.setText("RA");

        MostrarSenhaToggleButton.setText("Mostrar senha");
        MostrarSenhaToggleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MostrarSenhaToggleButtonActionPerformed(evt);
            }
        });

        txtFieldRA.setForeground(new java.awt.Color(204, 204, 204));
        txtFieldRA.setText("Digite o RA"); // NOI18N
        txtFieldRA.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtFieldRAFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtFieldRAFocusLost(evt);
            }
        });
        txtFieldRA.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtFieldRAMouseClicked(evt);
            }
        });

        lblResposta.setForeground(new java.awt.Color(255, 0, 0));
        lblResposta.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        EmprestarToggleButton.setText("Emprestar");
        EmprestarToggleButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                EmprestarToggleButtonMouseClicked(evt);
            }
        });

        jLabel2.setText("Senha");

        jButton2.setText("Para bibliotecários");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButton2MousePressed(evt);
            }
        });

        jLabel3.setText("Biblioteca IFPR - Campus Paranavaí");

        jLabel4.setText("Ou");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Armário 1", "Armário 2", "Armário 3", "Armário 4" }));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(86, 86, 86)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtFieldRA, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(passFieldSenha, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(MostrarSenhaToggleButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(EmprestarToggleButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jLabel4)
                                    .addGap(18, 18, 18)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(DevolverToggleButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jComboBox1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(172, 172, 172)
                        .addComponent(AcessarButton))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(119, 119, 119)
                        .addComponent(jLabel3))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(152, 152, 152)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblResposta)
                            .addComponent(jButton2))))
                .addContainerGap(106, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtFieldRA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(passFieldSenha, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(MostrarSenhaToggleButton)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(DevolverToggleButton)
                    .addComponent(EmprestarToggleButton))
                .addGap(18, 18, 18)
                .addComponent(AcessarButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblResposta)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2)
                .addContainerGap(43, Short.MAX_VALUE))
        );

        passFieldSenha.getAccessibleContext().setAccessibleDescription("");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MostrarSenhaToggleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MostrarSenhaToggleButtonActionPerformed
        if(!passFieldSenha.getText().equals("Digite a senha")) {
            if(MostrarSenhaToggleButton.isSelected()) {
                passFieldSenha.setEchoChar((char)0);
            } else {
                passFieldSenha.setEchoChar('*');
            }
        } else {
            MostrarSenhaToggleButton.setSelected(false);
        }
    }//GEN-LAST:event_MostrarSenhaToggleButtonActionPerformed

    private void passFieldSenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passFieldSenhaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passFieldSenhaActionPerformed

    private void txtFieldRAFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtFieldRAFocusLost
        if(txtFieldRA.getText().equals("")) {
            txtFieldRA.setText("Digite o RA");
            txtFieldRA.setForeground(new Color(204, 204, 204));
        }
    }//GEN-LAST:event_txtFieldRAFocusLost

    private void txtFieldRAFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtFieldRAFocusGained
        if(txtFieldRA.getText().equals("Digite o RA")) {
            txtFieldRA.setText("");
            txtFieldRA.setForeground(new Color(0, 0, 0));
        }
    }//GEN-LAST:event_txtFieldRAFocusGained

    private void jButton2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MousePressed
        Bibliotecario bibliotecarioIndex = new Bibliotecario();
        this.setVisible(false);
        bibliotecarioIndex.setVisible(true);
    }//GEN-LAST:event_jButton2MousePressed

    private void DevolverToggleButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DevolverToggleButtonMouseClicked
        if(EmprestarToggleButton.isSelected()) {
            EmprestarToggleButton.setSelected(false);
        } else {
            DevolverToggleButton.setSelected(true);
        }
    }//GEN-LAST:event_DevolverToggleButtonMouseClicked

    private void EmprestarToggleButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EmprestarToggleButtonMouseClicked
        if(DevolverToggleButton.isSelected()) {
            DevolverToggleButton.setSelected(false);
        } else {
            EmprestarToggleButton.setSelected(true);
        }
    }//GEN-LAST:event_EmprestarToggleButtonMouseClicked

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        EmprestarToggleButton.setSelected(true);
        passFieldSenha.setEchoChar((char)0);
    }//GEN-LAST:event_formWindowOpened

    private void passFieldSenhaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_passFieldSenhaFocusGained
        if(passFieldSenha.getText().equals("Digite a senha")) {
            passFieldSenha.setEchoChar('*');
            passFieldSenha.setText("");
            passFieldSenha.setForeground(Color.black);
        }
    }//GEN-LAST:event_passFieldSenhaFocusGained

    private void passFieldSenhaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_passFieldSenhaFocusLost
        if(passFieldSenha.getText().equals("")) {
            passFieldSenha.setEchoChar((char) 0);
            MostrarSenhaToggleButton.setSelected(false);
            passFieldSenha.setText("Digite a senha");
            passFieldSenha.setForeground(new Color(204, 204, 204));
        }
    }//GEN-LAST:event_passFieldSenhaFocusLost

    private void AcessarButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AcessarButtonMouseClicked
        LoginController controle = new LoginController();
        String RA = this.txtFieldRA.getText();
        String armario = jComboBox1.getSelectedItem().toString();
        String senha = String.copyValueOf(this.passFieldSenha.getPassword());
        boolean devolverArmario;

        if(DevolverToggleButton.isSelected()) {
            devolverArmario = true;
        } else {
            devolverArmario = false;
        }

        String resposta = controle.loginVerificacaoArmario(RA, senha, armario, devolverArmario);
        if(resposta.equals("Armário emprestado!") || resposta.equals("Armário devolvido!")) {
            lblResposta.setForeground(Color.blue);
        } else {
            lblResposta.setForeground(Color.red);
        }
        lblResposta.setText(resposta);
    }//GEN-LAST:event_AcessarButtonMouseClicked

    private void jPanel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseClicked
        
    }//GEN-LAST:event_jPanel1MouseClicked

    private void txtFieldRAMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtFieldRAMouseClicked
        this.setFocusable(true);
    }//GEN-LAST:event_txtFieldRAMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Index.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Index.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Index.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Index.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Index().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AcessarButton;
    private javax.swing.JToggleButton DevolverToggleButton;
    private javax.swing.JToggleButton EmprestarToggleButton;
    private javax.swing.JToggleButton MostrarSenhaToggleButton;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblResposta;
    private javax.swing.JPasswordField passFieldSenha;
    private javax.swing.JTextField txtFieldRA;
    // End of variables declaration//GEN-END:variables
}
